### PR TITLE
Added Google Colab Demonstration to Readme

### PR DESCRIPTION
**Pull request by mattyjacks**
I made a Google Colab.

### CODE REVIEW

**Comment by mattyjacks** [comment]
I just added an addition to the example.

**Comment by afrkciymjt** [comment]
Thank you for your interest! We will review this

**Comment by mattyjacks** [comment]
Yeah the only thing untested is me adding 2 print statements to the example
default, one before and one after the quick report

**Comment by afrkciymjt** [comment]
Hi there, I updated the docs + internal code with new naming conventions that are a breaking change. Could you copy+paste your changes to the new readme and create a new PR? Then I can merge it.

**Pull request closed without merging**
